### ISSUE TITLE
why does memcached node search exclude current node?

### ISSUE THREAD

**Issue by thoughtcroft** [poise/application_ruby#59]
The memcached provider searches for nodes in the current chef environment with the provided role to configure into memcached.yml.  However it specifically excludes the current node unless no nodes are returned in which case it will add the current node if it has the role.

What is the thinking there?

If we want to add memcached to every app node for example, then an app with multiple nodes will generate cache misses since every memcached.yml will have a different list of servers and the cache hash algorithm will store any given value into a different server.

**Comment by coderanger** [comment]
This is no longer a feature in 4.0.pre.
