### ISSUE TITLE
database.yml template does not support the socket option

### ISSUE THREAD

**Issue by evaryont** [poise/application_ruby#62]
The mysql2 adapter connects to the UNIX socket specified if both the host and port is not specified, useful when mysql isn't connected to any TCP sockets, and is only listening on the UNIX socket.

So, I imagine that passing the path to the socket as so:

```ruby
application "my_rails_mysql_app" do
  # ...
  database do
    socket '/var/run/mysqld.sock'
    user 'my_rails_app'
    password 'god_mode'
  end
  # ...
end
```

would work.

**Comment by coderanger** [comment]
In 4.0.pre it passes all options directly to the resultant Yaml so you can set anything.
