### ISSUE TITLE
ERROR: IOError: Cannot open or read /home/chef-repo/cookbooks/iptables/metadata.rb!

### ISSUE THREAD

**Issue by mechanikalk** [poise/application_ruby#68]
When running:

knife cookbook site install application_ruby

I get:

Pristine copy branch (chef-vendor-iptables) exists, switching to it.
Downloading iptables from the cookbooks site at version 0.14.1 to /home/confucius/chef-repo/cookbooks/iptables.tar.gz
Cookbook saved: /home/confucius/chef-repo/cookbooks/iptables.tar.gz
Removing pre-existing version.
Uncompressing iptables version 0.14.1.
removing downloaded tarball
No changes made to iptables
Checking out the master branch.
ERROR: IOError: Cannot open or read /home/chef-repo/cookbooks/iptables/metadata.rb!

there is a metadata.json file but no metadata.rb file.  When I try and add the metadata.rb from github and re-run install the iptable folder is overwritten and the metadata.rb file is deleted.

**Comment by coderanger** [comment]
Not an issue with this cookbook.
