### ISSUE TITLE
Rails ENV Variables?

### ISSUE THREAD

**Issue by hhff** [poise/application_ruby#69]
Hi guys.

Loving this cookbook!  Really handy - but up I'm running into some issues setting up environment variables for my app.  Here's my app block:

```ruby
include_recipe "runit"
application 'myapp' do
  owner 'deploy'
  group 'deploy'
  path '/var/www/myapp'
  repository 'git@github.com:hhff/myapp.git'
  rails do
    bundler true
    # These will eventually be passed in via a data bag
    environment "SECRET_KEY_BASE" => "secretkeybase", "SECRET_TOKEN" => "secrettoken"
    database do
      adapter "sqlite3"
      database "db/production.sqlite3"
    end
  end
  unicorn do
    worker_processes 2
  end
end
```

Here's my Rails ```secrets.yml```

```ruby
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
```

However, after a cook, when I tail my logs I'm still seeing:

```
2015-01-23_16:09:23.61596 E, [2015-01-23T08:09:23.615720 #2586] ERROR -- : app error: Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml` (RuntimeError)
```

Any tips?  I'm happy to update the docs once I get this figured out...

**Comment by plorent** [comment]
'environment' is not an attribute parameter for the rails block. I think you need to look at: https://docs.chef.io/resource_env.html

**Comment by w-A-L-L-e** [comment]
This is a new feature in rails 4. Putting secret keys in environment var
for production increases security (a little;) )

On Friday, April 10, 2015, Peter Lorent <notifications@github.com> wrote:

> 'environment' is not an attribute parameter for the rails block. I think
> you need to look at: https://docs.chef.io/resource_env.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/poise/application_ruby/issues/69#issuecomment-91546358>
> .
>


-- 

*SIT BVBA * <http://www.sitweb.eu>

   - Phone: +32.486.11.88.36
   - Fax: +32.3.239.68.24
   - Mail: Walter@Schreppers.com

**Comment by coderanger** [comment]
This is now handled directly via the rails resource and the secrets properties.

**Comment by legolin** [comment]
@coderanger v3.0.2 does not seem support the secrets properties.  If I point my Berksfile at this repo, it complains that there is no metadata.rb and must not be a valid cookbook.  I'm sure it's something obvious: what am I missing to be able to use this newer cookbook?

**Comment by coderanger** [comment]
@legolin This cookbook is in the midst of a major-version-level rewrite, see https://coderanger.net/state-of-the-onion-may-26/ for info on using a prerelease version.
