### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by jesseadams** [poise/application_ruby#70]
Can you please version bump this in the supermarket?

Thanks!

**Comment by dluchinienoc** [comment]
Seconding the version bump requrest.

FWIW, we are using Berkshelf to manage our dependencies, and as a workaround have our Berksfile pointed directly at this repo (with appropriate version pinning) instead:
```
source 'https://supermarket.chef.io'

metadata
cookbook 'application_ruby', git: 'https://github.com/poise/application_ruby.git', ref: 'fde770d176b5d0519982e2ec93bcf2d1a3ad35bb'
```

**Comment by jesseadams** [comment]
I can second this work around. I was too sad about this workaround to post it. I am glad you did though.

**Comment by neclimdul** [comment]
+1

**Comment by coderanger** [comment]
The next release is going to be 4.0.
