### ISSUE TITLE
database.yml default template

### ISSUE THREAD

**Issue by quentindemetz** [poise/application_ruby#71]
If I don't specify `database_template` in the `rails` block, it doesn't use my default `database.yml.erb` template, but that's what the documentation says: https://supermarket.chef.io/cookbooks/application_ruby

**Comment by plorent** [comment]
No, if you do not specify it, the default.yml.erb template from the cookbook application_ruby will be used.

**Comment by quentindemetz** [comment]
The documentation reads:

>database_template: the name of the template that will be rendered to create the database.yml file; if specified it will be looked up in the application cookbook. Defaults to "**database.yml.erb**" from this cookbook

**Comment by plorent** [comment]
Yes, so 'if specified' -> you set it in the rails block in your application cookbook.
If not specified -> takes the database.yml.erb from application_ruby cookbook.

**Comment by quentindemetz** [comment]
Understood. Your first comment mentioned **default.yml.erb** which was confusing. Thanks for the clarification.

**Comment by plorent** [comment]
That was indeed confusing. Apologies for the typo.

**Comment by coderanger** [comment]
This is no longer an issue in the development version.

**Comment by quentindemetz** [comment]
@coderanger what do you mean by that? I can't see an example where I can specify my custom template file with the latest release. A hint would me warmly welcome :)

Thanks

**Comment by coderanger** [comment]
@quentindemetz You generally don't need to as the `database` property will convert everything inside its hash/block into the database.yml file, but you can override the default via `database_config_source 'nameottemplate.erb'`. You can see the default template at https://github.com/poise/application_ruby/blob/master/chef/templates/database.yml.erb
