### ISSUE TITLE
option to retry bundle install

### ISSUE THREAD

**Issue by quentindemetz** [poise/application_ruby#74]
I'm repeatedly encountering an issue where rubygems throws a 503 on one of my gems during the bundle install run. How would it be possible to retry that operation ?

Thanks !

**Comment by coderanger** [comment]
All resources support a `retries` property that should help in this situation.

**Comment by quentindemetz** [comment]
Does this mean it's enough to write this ?
```
rails do
    gems              ['bundler']
    database_template 'database.yml.erb'
    retries            5
end
```
Thanks

**Comment by coderanger** [comment]
That would be the old application cookbook, which I no longer support and wouldn't work with this. With the new `bundle_install` resource, the `retries` option should work as expected.

**Comment by quentindemetz** [comment]
Any idea when you're going to release the "new application cookbook" ? If I'm not mistaken, I don't see any releases here since 2013...
Thanks

**Comment by coderanger** [comment]
@quentindemetz I've been saying "tomorrow-ish" for about two weeks now, so that gives you some context. Got the next (and probably last) example app up and tested so running out of things to do before release!
