### ISSUE TITLE
Support SSL DB Connection Configs

### ISSUE THREAD

**Issue by hstrowd** [poise/application_ruby#75]
MySQL database connections can support SSL Connections using the `sslca`, `sslkey`, `sslcert`, `sslcapath`, and `sslcipher` configuration parameters (see http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/MysqlAdapter.html). I'd like to go ahead and add support for these to the database template.

**Comment by coderanger** [comment]
If you look, there isn't (really) a template anymore. All config options from the database block/hash are in the final Yaml.

**Comment by coderanger** [comment]
Specifically https://github.com/poise/application_ruby/blob/master/chef/templates/database.yml.erb is the database template now.
