### ISSUE TITLE
Add a metadata.rb file

### ISSUE THREAD

**Issue by dorongutman** [poise/application_ruby#85]
When trying to use a fork or a branch of this repo - berkshelf throws an error about `The resource at '/var/folders/wp/5vk87yqj74s6db15lbjn16qr0000gn/T/d20160515-60205-qblbms' does not appear to be a valid cookbook. Does it have a metadata.rb?"`

I also tried adding `extension 'halite'` to the top of the Berksfile file and using the dependency as a gem, but I'm getting the following: `/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/berkshelf-4.0.1/lib/berkshelf/berksfile.rb:89:in `rescue in extension': Could not load an extension by the name `halite'. Please make sure it is installed. (LoadError)`

**Comment by coderanger** [comment]
https://github.com/poise/halite#using-a-pre-release-version-of-a-cookbook

**Comment by coderanger** [comment]
This is almost never a good idea.
